name: Playwright Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm i

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chrome

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: document-pdf
          path: document.pdf
          retention-days: 7
